### ISSUE TITLE
Feature/Plugin Provider, Name and Id should be cleaned up

### ISSUE THREAD

**Issue by vorburger** [lastnpe/eclipse-external-annotations-m2e-plugin#19]
Both the Feature's & Plugin's Provider, Name and Id should be cleaned up:

* Provider: lastnpe.org instead of Sylvain & my name
* Provider in "Installed Software" (feature.feature.group) is empty
* Name: Something copy/pasted from somewhere around here, instead of "Maven Integration for Eclipse Settings"
* Id: org.lastnpe.m2e.feature instead of eclipse_external_annotations_m2e_plugin

@sylvainlaurent is this something you may be interested in doing?

**Comment by vorburger** [comment]
Note to self: When feature's ID changes, [adjust here accordingly](https://github.com/vorburger/opendaylight-eclipse-setup/commit/25d320c9468111d36ceb1792327b97b7aefe678c#diff-c6b57d6f928ec9659aedc6d9298e9ce9R1401).

**Comment by sylvainlaurent** [comment]
@vorburger OK for provider and name.
But are you sure you want to change the Id ? it would also require to change the groupId and artifactId in the various pom.xml. For instance `org.lastnpe.m2e` for groupId, but what for artifactId?

**Comment by vorburger** [comment]
done!
