### ISSUE TITLE
Make plugin compatible with Eclipse Photon 4.8 branch

### ISSUE THREAD

**Issue by nfekete** [lastnpe/eclipse-external-annotations-m2e-plugin#28]
The dependency versions of the m2e dependencies being restricted to [1.6.0,1.9.0) caused a problem that tricked me quite hard. The p2 conflict resolution somehow pulled in a strange ___Object Teams Patch for JDT/Core___ dependency by conflicting with the m2e versions declared in the newest JDT (I guess somehow confict resolution thought that pulling in that patch feature/plugin would resolve the dependency conflict, which it would probably do, at the cost of replacing the JDT with something else). So Eclipse would only update itself from 4.8 M3 with lastnpe present if the user would confirm replacing JDT with that obscure plugin. 

Searches on google for this problem gave no meaningful results about the problem (except similar, but unrelated issues) so I thought it would be valuable to be written here, so that people would be pointed in the right direction in case they would face similar problems, since it took me quite some time to figure out what was the problem.

The key to solve the above dependency problem was to release a version of this plugin with the m2e dependency versions relaxed to [1.6.0,2.0.0). It seems it doesn't break anything, though I'm not sure how to check it out properly.

**Comment by vorburger** [comment]
@nfekete hope you agree it's OK to close this issue now that we merged #29 ? Just re-open if NOK.

**Comment by nfekete** [comment]
I think it's right to close it. I've been using this with Photon M4 for a while, and I didn't have any issue. 
There's Photon M5 released just very recently, so I'm gonna go ahead and upgrade and see if there's any issue with it.
