### ISSUE TITLE
Not compatible with latest version of m2e

### ISSUE THREAD

**Issue by Ravynne** [lastnpe/eclipse-external-annotations-m2e-plugin#44]
So, I did an Eclipse update and probably shouldn't have. Anyway, I tried tinkering with the dependency requirements of the plugin and building it myself, but ended up breaking my installation. Here's the error when trying to install against the version on the update site.

Cannot complete the install because of a conflicting dependency.
  Software being installed: eclipse-external-annotations-m2e-plugin 1.0.0.201810042020 (org.lastnpe.m2e.feature.feature.group 1.0.0.201810042020)
  Software currently installed: M2E - Maven Integration for Eclipse 2.0.4.20220904-1703 (org.eclipse.m2e.feature.feature.group 2.0.4.20220904-1703)
  Only one of the following can be installed at once: 
    Maven Integration for Eclipse 1.9.0.20180606-2036 (org.eclipse.m2e.core 1.9.0.20180606-2036)
    M2E Maven Integration for Eclipse Core 2.0.3.20220904-1703 (org.eclipse.m2e.core 2.0.3.20220904-1703)
    M2E Maven Integration for Eclipse Core 1.18.4.20220208-0831 (org.eclipse.m2e.core 1.18.4.20220208-0831)
  Cannot satisfy dependency:
    From: M2E - Maven Integration for Eclipse 2.0.4.20220904-1703 (org.eclipse.m2e.feature.feature.group 2.0.4.20220904-1703)
    To: org.eclipse.equinox.p2.iu; org.eclipse.m2e.core [2.0.3.20220904-1703,2.0.3.20220904-1703]
  Cannot satisfy dependency:
    From: eclipse-external-annotations-m2e-plugin 1.0.0.201810042020 (org.lastnpe.m2e.core 1.0.0.201810042020)
    To: osgi.bundle; org.eclipse.m2e.core [1.6.0,2.0.0)
  Cannot satisfy dependency:
    From: eclipse-external-annotations-m2e-plugin 1.0.0.201810042020 (org.lastnpe.m2e.feature.feature.group 1.0.0.201810042020)
    To: org.eclipse.equinox.p2.iu; org.lastnpe.m2e.core [1.0.0.201810042020,1.0.0.201810042020]

**Comment by agentgt** [comment]
It looks like someone just needs to change this line:

https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/blob/52df50c1c71507b0a5026aad7ac9d795e06e2094/eclipse-external-annotations-m2e-plugin.core/META-INF/MANIFEST.MF#L11

Its been a long time since I have used osgi but I think that is what is needed.

**Comment by Ravynne** [comment]
Hoping it would be easy, I changed it to 3.0.0), and then when I updated a Maven project, I get the error below. I haven't done plugin development, so I wouldn't know where to begin on fixing this. But hmm, is this a Java 9 thing now with modules?

An internal error occurred during: "Updating Maven Project".
loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @15b4517 wants to load class org.apache.maven.project.MavenProject. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @6282f1eb. (org.apache.maven.project.MavenProject is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6282f1eb, parent loader 'platform')

**Comment by Ravynne** [comment]
So besides the error, I *think* it's still working however. No compiler warnings regarding nulls...

Anyway, here's the resulting Eclipse log trace

```
!ENTRY org.eclipse.core.jobs 4 2 2022-09-22 15:44:56.401
!MESSAGE An internal error occurred during: "Updating Maven Dependencies".
!STACK 0
java.lang.LinkageError: loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1baa0474 wants to load class org.apache.maven.project.MavenProject. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @7e89eba7. (org.apache.maven.project.MavenProject is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @7e89eba7, parent loader 'platform')
	at org.lastnpe.m2e.core.configurator.ClasspathConfigurator.getSingleProjectWideAnnotationPath(ClasspathConfigurator.java:344)
	at org.lastnpe.m2e.core.configurator.ClasspathConfigurator.getSingleProjectWideAnnotationPath(ClasspathConfigurator.java:332)
	at org.lastnpe.m2e.core.configurator.ClasspathConfigurator.mavenProjectChanged(ClasspathConfigurator.java:468)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:857)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:827)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:982)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob.lambda$0(ProjectRegistryRefreshJob.java:170)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:205)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob.run(ProjectRegistryRefreshJob.java:104)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by agentgt** [comment]
Maybe try this persons PR: https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/pull/42/commits/ecd10b349c6d750a30344c00928c42e3d7fa6022

(btw I'm not a project maintainer... my eclipse plugin dev knowledge is sadly poor but I rely on this plugin so I subscribe to changes).

When I upgrade I'll be in the same boat as you!

**Comment by Ravynne** [comment]
That PR was very promising. But I went down a rabbit hole of having to guess at updating dependencies and then introducing Java 17 and records and then not being able to find a way to convert from one object to another... So anyway, I can't spend any more time hacking at this. This is just outside my comfort zone.
