### ISSUE TITLE
Update the P2-Update Site

### ISSUE THREAD

**Issue by askpythia** [lastnpe/eclipse-external-annotations-m2e-plugin#47]
Please update the http://www.lastnpe.org/eclipse-external-annotations-m2e-plugin-p2-site for M2E 2.x
Additional Tip: Extend the Dependency range to support both, M2E 1.x and M2E 2.x so that all installations (Current 2022-09 and older) can use this plugin (we use it via OOMPH setup).

**Comment by wborn** [comment]
Eclipse 2022-12 uses org.eclipse.m2e.maven.runtime 3.8.602.20221112-1947

Oomph shows this error when installing the plugin:

```
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1669562279310
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: eclipse-external-annotations-m2e-plugin 1.0.0.201810042020 (org.lastnpe.m2e.core 1.0.0.201810042020) requires 'osgi.bundle; org.eclipse.m2e.maven.runtime [1.6.0,2.0.0)' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1669562279310
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.lastnpe.m2e.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: eclipse-external-annotations-m2e-plugin 1.0.0.201810042020 (org.lastnpe.m2e.feature.feature.group 1.0.0.201810042020)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.lastnpe.m2e.core [1.0.0.201810042020,1.0.0.201810042020]
```

**Comment by kaikreuzer** [comment]
@vorburger How did you deploy the p2 site? Is it enough to add the content to https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin-p2-site?

Unfortunately, the latest code of this repo does not build for me - I get this error:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:3.0.0:assemble-repository (default-assemble-repository) on project site: Execution default-assemble-repository of goal org.eclipse.tycho:tycho-p2-repository-plugin:3.0.0:assemble-repository failed: An API incompatibility was encountered while executing org.eclipse.tycho:tycho-p2-repository-plugin:3.0.0:assemble-repository: java.lang.NoSuchMethodError: 'void org.eclipse.equinox.internal.p2.repository.helpers.ChecksumProducer.<init>(java.lang.String, java.lang.String, java.lang.String)'
```
So if someone else is able to build it and add it to the site (in an additional sub-folder), it would be awesome!

**Comment by wborn** [comment]
Maybe @arathai can help because fixing this will probably be very similar to #45. :slightly_smiling_face:

**Comment by kaikreuzer** [comment]
Well, I checked out the latest version that contains #45, so yes, I guess the problem is on my side (I tried it with Java 11, 17 and 19, but no luck) and others like @arathai were able to build it successfully.

**Comment by wborn** [comment]
I gave it a test myself and after changing this version to 3.0.1 it seems to build:

https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/blob/57e26f49d89d50c451497ad1c633fc1fca9d2637/pom.xml#L25

**Comment by kaikreuzer** [comment]
Indeed! -> https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/pull/48

**Comment by wborn** [comment]
> How did you deploy the p2 site? Is it enough to add the content to https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin-p2-site?

It looks like it was deployed to GitHub pages by Travis CI once upon a time, see:

* https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/blob/master/.travis.yml
* https://docs.travis-ci.com/user/deployment/pages/

**Comment by kaikreuzer** [comment]
@wborn Shall we have a try with https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin-p2-site/pull/1 and then see how it can be deployed?

**Comment by wborn** [comment]
Yes let's give it a try. :+1:

**Comment by vorburger** [comment]
@kaikreuzer @wborn I'm very happy to see you that you are "carrying the torch forward" here. (I currently do not use this anymore myself.) This is Open Source at its best!

**Comment by wborn** [comment]
It seems to install fine now using the new update site with Oomph and Eclipse 2022-12.
If the URL for the update site is final it would also be nice to make it more discoverable by adding it to the [README.md](https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/blob/master/README.md).
Perhaps the version should also be changed from 1.x to 2.x because of all the new requirements like Java 17?

![Screenshot from 2022-12-10 22-47-43](https://user-images.githubusercontent.com/12213581/206876497-b824df48-106a-4303-b942-1f1fdb3c7074.png)

**Comment by kaikreuzer** [comment]
Makes sense. Do you want to create a PR for it? I'll happily review and merge it then. 😄

**Comment by wborn** [comment]
As you may have noticed, I have created #49 for these changes.
