### ISSUE TITLE
Rename GAV + packages to replace "sylvainlaurent" by lastnpe

### ISSUE THREAD

**Issue by sylvainlaurent** [lastnpe/eclipse-external-annotations-m2e-plugin#7]
maven groupId : com.github.lastnpe.m2e

packages : com.github.lastnpe.m2e.*

@vorburger : ok for you ?

**Comment by vorburger** [comment]
@sylvainlaurent yeah, but could you please use org.lastnpe.m2e instead of com.github?

FYI: I actually bought http://www.lastnpe.org earlier today.. ;-)

The theory is that maybe in 100 years this won't be on GitHub, anymore... :-)

**Comment by vorburger** [comment]
Done by merge of https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/pull/9
